# Generated by Django 3.2.2 on 2021-05-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=101),
            preserve_default=False,
        ),
    ]
